# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='interval',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
