# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_trip_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='completed',
        ),
    ]
